"""Security tests for generated-action review packets."""

from __future__ import annotations

from pathlib import Path

from services.review_packets import ReviewPacketService, build_generated_script, render_review_packet
from services.staging_store import StagingStore


def test_generated_script_is_staged_not_executed(tmp_path: Path):
    # Staging a script must never execute it. This prevents prompt-injected shell
    # text from creating files merely because a review packet was generated.
    side_effect = tmp_path / "executed.txt"
    service = ReviewPacketService(StagingStore(tmp_path / "staging"))

    script, packet = service.stage_generated_script(
        f"touch {side_effect}",
        requested_goal="create a marker",
        tool_name="shell.run",
        risk_level="Critical",
        why_risky="Shell commands can modify the host.",
        files_touched=[str(side_effect)],
        network_access="none",
    )

    assert script.path.exists()
    assert packet.artifact.path.exists()
    assert not side_effect.exists()
    assert "Reviewed by user: no" in script.path.read_text()


def test_generated_script_header_includes_required_review_fields():
    # The script header makes risk properties visible even when a reviewer opens
    # only the generated script and not the separate review packet.
    script = build_generated_script(
        "echo hello",
        risk_level="High",
        requires_sudo=True,
        writes_files=True,
        network_access=True,
        dry_run_supported=False,
    )

    assert script.startswith("#!/usr/bin/env bash")
    assert "# Generated by Odysseus" in script
    assert "# Risk Level: High" in script
    assert "# Requires sudo: yes" in script
    assert "# Writes files: yes" in script
    assert "# Network access: yes" in script
    assert "# Dry-run supported: no" in script
    assert "# Reviewed by user: no" in script
    assert "set -euo pipefail" in script


def test_review_packet_includes_verification_and_rollback_sections():
    # Review packets must contain the operational details needed to safely accept
    # or reject a high-risk generated action.
    packet = render_review_packet(
        requested_goal="rotate logs",
        tool_name="shell.run",
        risk_level="Critical",
        why_risky="Can delete files.",
        verification="Check service logs after rotation.",
        rollback="Restore log directory from backup.",
    )

    assert "## Verification" in packet
    assert "Check service logs after rotation." in packet
    assert "## Rollback" in packet
    assert "Restore log directory from backup." in packet
    assert "## Human Decision" in packet


def test_review_packet_includes_tool_risk_network_and_files():
    # Reviewers need the tool, risk, network access, and file list before making
    # a human approval decision.
    packet = render_review_packet(
        requested_goal="send report",
        tool_name="email.send",
        risk_level="High",
        why_risky="Could send private content externally.",
        files_touched=["data/generated/report.md", "data/uploads/source.txt"],
        network_access="SMTP server",
    )

    assert "## Tool\nemail.send" in packet
    assert "## Risk Level\nHigh" in packet
    assert "## Network Access\nSMTP server" in packet
    assert "- data/generated/report.md" in packet
    assert "- data/uploads/source.txt" in packet


def test_review_packet_is_staged_as_markdown(tmp_path: Path):
    # Review packets should be persisted as drafts, not returned only in memory
    # where they cannot be inspected later.
    service = ReviewPacketService(StagingStore(tmp_path / "staging"))

    packet = service.create_review_packet(
        requested_goal="update config",
        tool_name="file.write",
        risk_level="High",
        why_risky="Writes configuration files.",
        proposed_changes="Change setting A to B.",
    )

    assert packet.artifact.artifact_type == "command-review"
    assert packet.artifact.path.suffix == ".md"
    assert packet.artifact.path.read_text() == packet.markdown
    assert "# Odysseus Action Review" in packet.markdown


def test_review_packet_audit_hook_is_emitted(tmp_path: Path):
    # Provides a low-risk hook for later tool_audit integration without making
    # packet generation depend on a concrete audit store.
    events: list[tuple[str, dict[str, object]]] = []
    service = ReviewPacketService(
        StagingStore(tmp_path / "staging"),
        audit_hook=lambda event, metadata: events.append((event, metadata)),
    )

    packet = service.create_review_packet(
        requested_goal="inspect command",
        tool_name="shell.run",
        risk_level="Critical",
        why_risky="Shell execution changes host state.",
    )

    assert ("review_packet_generated", {"packet_id": packet.packet_id}) in events
