"""
Review packet and confirmation-token helpers for staged Odysseus actions.

This module turns generated scripts, commands, and other high-risk proposals into
reviewable markdown packets. It also provides a minimal action-bound,
single-use confirmation token store used by tests and later approval flows.
"""

from __future__ import annotations

import hashlib
import secrets
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Callable, Iterable

from services.staging_store import StagedArtifact, StagingStore


class ReviewPacketError(ValueError):
    """Raised when review packet generation or confirmation validation fails."""


@dataclass(frozen=True)
class ReviewPacket:
    """
    Metadata for a generated action review packet.

    Attributes:
        packet_id: Server-generated packet artifact ID.
        artifact: Staged packet artifact metadata.
        markdown: Review packet markdown content.
    """

    packet_id: str
    artifact: StagedArtifact
    markdown: str


@dataclass(frozen=True)
class ConfirmationToken:
    """
    Action-bound confirmation token metadata.

    Attributes:
        token_id: Opaque token value returned to the approval flow.
        user_id: User identity the token is bound to.
        session_id: Session identity the token is bound to.
        tool_name: Tool the token authorizes.
        decision_id: Policy decision the token is bound to.
        content_hash: Hash of the reviewed content.
        expires_at: UTC expiration timestamp.
        used: Whether the token has already been consumed.
    """

    token_id: str
    user_id: str
    session_id: str
    tool_name: str
    decision_id: str
    content_hash: str
    expires_at: datetime
    used: bool = False


AuditHook = Callable[[str, dict[str, object]], None]


def content_hash(content: str | bytes) -> str:
    """
    Hash staged or reviewed content for action-bound confirmations.

    Args:
        content: Text or bytes representing the reviewed action.

    Returns:
        Hex-encoded SHA-256 digest.
    """
    data = content.encode("utf-8") if isinstance(content, str) else bytes(content)
    return hashlib.sha256(data).hexdigest()


def build_generated_script(
    body: str,
    *,
    risk_level: str,
    requires_sudo: bool = False,
    writes_files: bool = False,
    network_access: bool = False,
    dry_run_supported: bool = False,
) -> str:
    """
    Build a generated shell script with an explicit review header.

    Args:
        body: Shell body to stage as a draft.
        risk_level: Medium, High, or Critical risk label.
        requires_sudo: Whether the script proposes sudo use.
        writes_files: Whether the script proposes writing files.
        network_access: Whether the script proposes network access.
        dry_run_supported: Whether the script supports dry-run mode.

    Returns:
        Draft shell script text. The function does not execute the script.
    """
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "# Generated by Odysseus",
            f"# Risk Level: {risk_level}",
            f"# Requires sudo: {'yes' if requires_sudo else 'no'}",
            f"# Writes files: {'yes' if writes_files else 'no'}",
            f"# Network access: {'yes' if network_access else 'no'}",
            f"# Dry-run supported: {'yes' if dry_run_supported else 'no'}",
            "# Reviewed by user: no",
            "set -euo pipefail",
            "",
            body.rstrip(),
            "",
        ]
    )


def _format_lines(values: Iterable[str]) -> str:
    """
    Render a list of review values as markdown bullets.

    Args:
        values: Values to render.

    Returns:
        Bullet list or ``- none`` when empty.
    """
    items = [str(value) for value in values if str(value)]
    if not items:
        return "- none"
    return "\n".join(f"- {item}" for item in items)


def render_review_packet(
    *,
    requested_goal: str,
    tool_name: str,
    risk_level: str,
    why_risky: str,
    proposed_read_only_checks: Iterable[str] = (),
    proposed_changes: str = "",
    files_touched: Iterable[str] = (),
    network_access: str = "none",
    commands_not_approved: Iterable[str] = (),
    required_backup_or_snapshot: str = "not required",
    verification: str = "Reviewer must define verification before approval.",
    rollback: str = "Reviewer must define rollback before approval.",
    human_decision: str = "pending",
) -> str:
    """
    Render an Odysseus action review packet.

    Args:
        requested_goal: User-visible goal for the proposed action.
        tool_name: Tool associated with the staged action.
        risk_level: Risk level from the tool policy registry.
        why_risky: Plain-language risk explanation.
        proposed_read_only_checks: Safe checks a reviewer can run first.
        proposed_changes: Summary of proposed changes or staged artifact content.
        files_touched: Files expected to be read or written.
        network_access: Network access requested by the action.
        commands_not_approved: Commands explicitly not approved for execution.
        required_backup_or_snapshot: Backup or snapshot expectation.
        verification: Reviewer-facing verification instructions.
        rollback: Reviewer-facing rollback instructions.
        human_decision: Approval state, defaulting to pending.

    Returns:
        Markdown review packet.
    """
    return f"""# Odysseus Action Review

## Requested Goal
{requested_goal}

## Tool
{tool_name}

## Risk Level
{risk_level}

## Why This Is Risky
{why_risky}

## Proposed Read-Only Checks
{_format_lines(proposed_read_only_checks)}

## Proposed Changes
{proposed_changes or 'No changes supplied.'}

## Files Touched
{_format_lines(files_touched)}

## Network Access
{network_access}

## Commands Not Approved
{_format_lines(commands_not_approved)}

## Required Backup or Snapshot
{required_backup_or_snapshot}

## Verification
{verification}

## Rollback
{rollback}

## Human Decision
{human_decision}
"""


class ReviewPacketService:
    """
    Create staged artifacts and markdown review packets.

    The service writes drafts only. It intentionally does not execute generated
    scripts, shell commands, email sends, or patches after creating a packet.
    """

    def __init__(self, staging_store: StagingStore, *, audit_hook: AuditHook | None = None) -> None:
        """
        Initialize the review packet service.

        Args:
            staging_store: Filesystem staging store used for persistence.
            audit_hook: Optional event callback for later audit integration.
        """
        self.staging_store = staging_store
        self.audit_hook = audit_hook

    def stage_generated_script(
        self,
        body: str,
        *,
        requested_goal: str,
        tool_name: str,
        risk_level: str,
        why_risky: str,
        files_touched: Iterable[str] = (),
        network_access: str = "none",
        verification: str = "Run the proposed read-only checks, inspect output, and verify expected files only.",
        rollback: str = "Reject the packet or restore from the required backup before retrying.",
    ) -> tuple[StagedArtifact, ReviewPacket]:
        """
        Stage a generated shell script and create its review packet.

        Args:
            body: Shell body to place behind the generated-script header.
            requested_goal: User-visible goal of the proposal.
            tool_name: Tool associated with this script.
            risk_level: Risk level label.
            why_risky: Reviewer's risk explanation.
            files_touched: Files the proposal expects to touch.
            network_access: Network access requested by the action.
            verification: Verification instructions for reviewers.
            rollback: Rollback instructions for reviewers.

        Returns:
            Tuple of staged script artifact and staged review packet.
        """
        touched_files = list(files_touched)
        script = build_generated_script(
            body,
            risk_level=risk_level,
            requires_sudo="sudo" in body,
            writes_files=bool(touched_files),
            network_access=network_access.lower() not in {"", "none", "no"},
            dry_run_supported="--dry-run" in body or "DRY_RUN" in body,
        )
        script_artifact = self.staging_store.stage_artifact("generated-script", script, extension=".sh")

        packet = self.create_review_packet(
            requested_goal=requested_goal,
            tool_name=tool_name,
            risk_level=risk_level,
            why_risky=why_risky,
            proposed_changes=f"Generated script staged at `{script_artifact.relative_path}`.",
            files_touched=touched_files,
            network_access=network_access,
            commands_not_approved=[body.strip()],
            verification=verification,
            rollback=rollback,
        )
        self._emit(
            "tool_staged",
            {"artifact_id": script_artifact.artifact_id, "packet_id": packet.packet_id, "tool_name": tool_name},
        )
        return script_artifact, packet

    def create_review_packet(self, **kwargs: object) -> ReviewPacket:
        """
        Create and stage a markdown review packet.

        Args:
            **kwargs: Keyword arguments accepted by ``render_review_packet``.

        Returns:
            Review packet metadata and markdown.
        """
        markdown = render_review_packet(**kwargs)  # type: ignore[arg-type]
        artifact = self.staging_store.stage_artifact("command-review", markdown, extension=".md")
        packet = ReviewPacket(packet_id=artifact.artifact_id, artifact=artifact, markdown=markdown)
        self._emit("review_packet_generated", {"packet_id": packet.packet_id})
        return packet

    def _emit(self, event_type: str, metadata: dict[str, object]) -> None:
        """
        Emit an optional audit hook for staging/review packet events.

        Args:
            event_type: Event name such as ``review_packet_generated``.
            metadata: Event metadata.
        """
        if self.audit_hook is not None:
            self.audit_hook(event_type, metadata)


class ConfirmationTokenStore:
    """
    Minimal in-memory confirmation-token store.

    Tokens are bound to user, session, tool, policy decision, and content hash.
    They are single-use and time-limited so approving one reviewed artifact
    cannot approve a later or different action.
    """

    def __init__(self, *, ttl_seconds: int = 900) -> None:
        """
        Initialize an in-memory token store.

        Args:
            ttl_seconds: Token lifetime in seconds.
        """
        self.ttl_seconds = ttl_seconds
        self._tokens: dict[str, ConfirmationToken] = {}

    def issue(
        self,
        *,
        user_id: str,
        session_id: str,
        tool_name: str,
        decision_id: str,
        content: str | bytes,
        now: datetime | None = None,
    ) -> ConfirmationToken:
        """
        Issue a confirmation token for one reviewed action.

        Args:
            user_id: User identity the token is bound to.
            session_id: Session identity the token is bound to.
            tool_name: Tool the token authorizes.
            decision_id: Policy decision associated with the review.
            content: Reviewed action content.
            now: Optional timestamp for tests.

        Returns:
            Confirmation token metadata.
        """
        created_at = now or datetime.now(timezone.utc)
        token = ConfirmationToken(
            token_id=secrets.token_urlsafe(32),
            user_id=user_id,
            session_id=session_id,
            tool_name=tool_name,
            decision_id=decision_id,
            content_hash=content_hash(content),
            expires_at=created_at + timedelta(seconds=self.ttl_seconds),
            used=False,
        )
        self._tokens[token.token_id] = token
        return token

    def consume(
        self,
        token_id: str,
        *,
        user_id: str,
        session_id: str,
        tool_name: str,
        decision_id: str,
        content: str | bytes,
        now: datetime | None = None,
    ) -> ConfirmationToken:
        """
        Consume a confirmation token if it matches the reviewed action.

        Args:
            token_id: Opaque token value to consume.
            user_id: User attempting approval.
            session_id: Session attempting approval.
            tool_name: Tool being approved.
            decision_id: Policy decision being approved.
            content: Action content being approved.
            now: Optional timestamp for tests.

        Returns:
            The consumed token metadata.

        Raises:
            ReviewPacketError: If the token is missing, expired, used, or bound
                to a different action context.
        """
        token = self._tokens.get(token_id)
        if token is None:
            raise ReviewPacketError("confirmation token not found")
        if token.used:
            raise ReviewPacketError("confirmation token has already been used")

        current_time = now or datetime.now(timezone.utc)
        if current_time > token.expires_at:
            raise ReviewPacketError("confirmation token expired")

        expected = (
            token.user_id,
            token.session_id,
            token.tool_name,
            token.decision_id,
            token.content_hash,
        )
        actual = (
            user_id,
            session_id,
            tool_name,
            decision_id,
            content_hash(content),
        )
        if actual != expected:
            raise ReviewPacketError("confirmation token does not match reviewed action")

        consumed = ConfirmationToken(
            token_id=token.token_id,
            user_id=token.user_id,
            session_id=token.session_id,
            tool_name=token.tool_name,
            decision_id=token.decision_id,
            content_hash=token.content_hash,
            expires_at=token.expires_at,
            used=True,
        )
        self._tokens[token_id] = consumed
        return consumed
